import type { CMMIData } from '@/types';

const today = new Date();
const meetingDate = new Date(today);
// Set to a weekday to be more realistic
meetingDate.setDate(today.getDate() + (today.getDay() === 5 ? 3 : today.getDay() === 6 ? 2 : 1));


export const defaultData: CMMIData = {
  companyName: "TechGrowth Solutions",
  meetingDate: meetingDate.toISOString().split('T')[0],
  serviceType: "Agilean",
  cmmiModel: "Development",
  maturityLevel: "ML3 - Defined",
  businessLine: "Software Development & IT Services",
  peopleStrength: 100,
  projectScope: 10,
  locations: [{ name: "Mumbai, India" }],
  projectCharter: 1,
  overviewTraining: 2,
  stakeholders: 12,
  virtualTraining: 1,
  planningTraining: 0.5,
  assessmentExam: 0.5,
  cmmiVersion: "V3.0",
  cmmiPreparation: 25,
  rgsDocumentation: 40,
  evidenceTraining: 1,
  appraisalTraining: 3,
  projectManagement: 5,
  consultants: [{ name: "John Smith", email: "john.smith@abccompany.com" }],
  projectManagers: [{ name: "Sarah Johnson", email: "sarah.johnson@abccompany.com" }],
};

export const practiceAreas = {
  development: [
    { abbr: "RDM", name: "Requirement Development and Management" },
    { abbr: "PQA", name: "Process Quality Assurance" },
    { abbr: "VV", name: "Verification and Validation" },
    { abbr: "PR", name: "Peer Review" },
    { abbr: "TS", name: "Technical Solution" },
    { abbr: "PI", name: "Product Integration" },
    { abbr: "EST", name: "Estimation" },
    { abbr: "PLAN", name: "Planning" },
    { abbr: "MC", name: "Monitoring and Control" },
    { abbr: "RSK", name: "Risk and Opportunity Management" },
    { abbr: "OT", name: "Organizational Training" },
    { abbr: "CAR", name: "Causal Analysis and Resolution" },
    { abbr: "DAR", name: "Decision Analysis and Resolution" },
    { abbr: "CM", name: "Configuration Management" },
    { abbr: "GOV", name: "Governance" },
    { abbr: "II", name: "Implementation Infrastructure" },
    { abbr: "PCM", name: "Process Management" },
    { abbr: "PAD", name: "Process Asset Development" },
    { abbr: "MPM", name: "Managing Performance and Management" },
  ],
  services: [
    { abbr: "RDM", name: "Requirement Development and Management" },
    { abbr: "PQA", name: "Process Quality Assurance" },
    { abbr: "VV", name: "Verification and Validation" },
    { abbr: "PR", name: "Peer Review" },
    { abbr: "SDM", name: "Service Delivery Management" },
    { abbr: "CONT", name: "Continuity" },
    { abbr: "IRP", name: "Incident Resolution and Prevention" },
    { abbr: "STSM", name: "Strategic Service Management" },
    { abbr: "EST", name: "Estimation" },
    { abbr: "PLAN", name: "Planning" },
    { abbr: "MC", name: "Monitoring and Control" },
    { abbr: "RSK", name: "Risk and Opportunity Management" },
    { abbr: "OT", name: "Organizational Training" },
    { abbr: "CAR", name: "Causal Analysis and Resolution" },
    { abbr: "DAR", name: "Decision Analysis and Resolution" },
    { abbr: "CM", name: "Configuration Management" },
    { abbr: "GOV", name: "Governance" },
    { abbr: "II", name: "Implementation Infrastructure" },
    { abbr: "PCM", name: "Process Management" },
    { abbr: "PAD", name: "Process Asset Development" },
    { abbr: "MPM", name: "Managing Performance and Management" },
  ],
  multimodel: [
    { abbr: "RDM", name: "Requirement Development and Management" },
    { abbr: "PQA", name: "Process Quality Assurance" },
    { abbr: "VV", name: "Verification and Validation" },
    { abbr: "PR", name: "Peer Review" },
    { abbr: "TS", name: "Technical Solution" },
    { abbr: "PI", name: "Product Integration" },
    { abbr: "SDM", name: "Service Delivery Management" },
    { abbr: "CONT", name: "Continuity" },
    { abbr: "IRP", name: "Incident Resolution and Prevention" },
    { abbr: "STSM", name: "Strategic Service Management" },
    { abbr: "EST", name: "Estimation" },
    { abbr: "PLAN", name: "Planning" },
    { abbr: "MC", name: "Monitoring and Control" },
    { abbr: "RSK", name: "Risk and Opportunity Management" },
    { abbr: "OT", name: "Organizational Training" },
    { abbr: "CAR", name: "Causal Analysis and Resolution" },
    { abbr: "DAR", name: "Decision Analysis and Resolution" },
    { abbr: "CM", name: "Configuration Management" },
    { abbr: "GOV", name: "Governance" },
    { abbr: "II", name: "Implementation Infrastructure" },
    { abbr: "PCM", name: "Process Management" },
    { abbr: "PAD", name: "Process Asset Development" },
    { abbr: "MPM", name: "Managing Performance and Management" },
  ],
};
